service_name: travis-pro
<<<<<<< HEAD
<<<<<<< HEAD
repo_token: elr2SHhMuEIDAOYYsW9YRxGINi5BXeOss
=======
repo_token: oYGl0iYEohAWtvrA8zTuEXUt9aislOPu9
>>>>>>> 1b18391 ( Integrating Coverals and coverage)
=======
repo_token: COVERALL_TOKEN
>>>>>>> 3b5f2f2 ( updating ch-Coveralls-coverage-#184581165)
